// <auto-generated />
using System;
using Amuse.Modules.Listener.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amuse.Modules.Listener.Persistence.Migrations
{
    [DbContext(typeof(ListenerDbContext))]
    [Migration("20260606024319_AddListenerProfilePresentationAndPreferences")]
    partial class AddListenerProfilePresentationAndPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("listener")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amuse.Domain.Listener.ListenerPreference", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool?>("AllowUnverifiedArtists")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_unverified_artists");

                    b.Property<bool>("SetDuringOnboarding")
                        .HasColumnType("boolean")
                        .HasColumnName("set_during_onboarding");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId");

                    b.ToTable("listener_preference", "listener");
                });

            modelBuilder.Entity("Amuse.Domain.Listener.ListenerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int?>("AvatarAccentSeed")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_accent_seed");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("listener_profile", "listener");
                });
#pragma warning restore 612, 618
        }
    }
}
