// <auto-generated />
using System;
using Amuse.Domain.Discovery;
using Amuse.Modules.Discovery.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amuse.Modules.Discovery.Persistence.Migrations
{
    [DbContext(typeof(DiscoveryDbContext))]
    [Migration("20260606161438_AddPlaylistKindMigrateLiked")]
    partial class AddPlaylistKindMigrateLiked
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discovery")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "discovery", "library_entry_kind", new[] { "saved_playlist", "saved_release" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "discovery", "playlist_kind", new[] { "user", "liked" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "discovery", "playlist_visibility", new[] { "private", "public" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amuse.Domain.Discovery.LibraryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<LibraryEntryKind>("Kind")
                        .HasColumnType("discovery.library_entry_kind")
                        .HasColumnName("kind");

                    b.Property<Guid>("ListenerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("listener_profile_id");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("saved_at");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("ListenerProfileId", "Kind");

                    b.HasIndex("ListenerProfileId", "Kind", "TargetId")
                        .IsUnique();

                    b.ToTable("library_entry", "discovery");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.LikedTrack", b =>
                {
                    b.Property<Guid>("ListenerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("listener_profile_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTimeOffset>("LikedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("liked_at");

                    b.HasKey("ListenerProfileId", "TrackId");

                    b.ToTable("liked_track", "discovery");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ForkedFromPlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("forked_from_playlist_id");

                    b.Property<int>("Kind")
                        .HasColumnType("discovery.playlist_kind")
                        .HasColumnName("kind");

                    b.Property<Guid>("OwnerListenerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_listener_profile_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<PlaylistVisibility>("Visibility")
                        .HasColumnType("discovery.playlist_visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("OwnerListenerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_playlist_owner_liked_unique")
                        .HasFilter("kind = 1");

                    b.HasIndex("Visibility", "Title");

                    b.ToTable("playlist", "discovery");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistFollow", b =>
                {
                    b.Property<Guid>("ListenerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("listener_profile_id");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<DateTimeOffset>("FollowedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("followed_at");

                    b.HasKey("ListenerProfileId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("playlist_follow", "discovery");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("playlist_id")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.HasKey("Id");

                    b.HasIndex("playlist_id", "Position")
                        .IsUnique();

                    b.HasIndex("playlist_id", "TrackId")
                        .IsUnique();

                    b.ToTable("playlist_item", "discovery");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistShareGrant", b =>
                {
                    b.Property<Guid>("playlist_id")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("granted_at");

                    b.HasKey("playlist_id", "Email");

                    b.ToTable("playlist_share_grant", "discovery");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistItem", b =>
                {
                    b.HasOne("Amuse.Domain.Discovery.Playlist", null)
                        .WithMany("Items")
                        .HasForeignKey("playlist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistShareGrant", b =>
                {
                    b.HasOne("Amuse.Domain.Discovery.Playlist", null)
                        .WithMany("ShareGrants")
                        .HasForeignKey("playlist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.Playlist", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ShareGrants");
                });
#pragma warning restore 612, 618
        }
    }
}
