// <auto-generated />
using System;
using Amuse.Domain.Catalog;
using Amuse.Modules.Catalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amuse.Modules.Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260601010704_AddReleaseCollaborators")]
    partial class AddReleaseCollaborators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "artist_visibility_tier", new[] { "unverified", "platform_verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "audio_transcode_job_status", new[] { "queued", "processing", "succeeded", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "release_collaborator_role", new[] { "featured" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "release_lifecycle_status", new[] { "draft", "processing", "ready", "published", "hidden", "archived" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "release_type", new[] { "single", "ep", "album", "compilation" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "track_lifecycle_status", new[] { "draft", "processing", "ready", "published", "hidden" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amuse.Domain.Catalog.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_key");

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("bio");

                    b.Property<string>("CoverKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cover_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ManagingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("managing_organization_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.Property<ArtistVisibilityTier>("VisibilityTier")
                        .HasColumnType("catalog.artist_visibility_tier")
                        .HasColumnName("visibility_tier");

                    b.HasKey("Id");

                    b.HasIndex("ManagingOrganizationId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("artist", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("CoverArtKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cover_art_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<ReleaseLifecycleStatus>("LifecycleStatus")
                        .HasColumnType("catalog.release_lifecycle_status")
                        .HasColumnName("lifecycle_status");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("ReleaseDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("release_date");

                    b.Property<Guid?>("ReleaseGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_group_id");

                    b.Property<ReleaseType>("ReleaseType")
                        .HasColumnType("catalog.release_type")
                        .HasColumnName("release_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("ReleaseGroupId");

                    b.HasIndex("ArtistId", "Slug")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "LifecycleStatus", "ReleaseDate");

                    b.ToTable("release", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseCollaborator", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<int>("Role")
                        .HasColumnType("catalog.release_collaborator_role")
                        .HasColumnName("role");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.HasKey("ReleaseId", "ArtistId", "Role");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ReleaseId", "DisplayOrder");

                    b.ToTable("release_collaborator", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.ToTable("release_group", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioMasterKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audio_master_key");

                    b.Property<string>("AudioStreamKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audio_stream_key");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<bool>("ExplicitFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("explicit_flag");

                    b.Property<TrackLifecycleStatus>("LifecycleStatus")
                        .HasColumnType("catalog.track_lifecycle_status")
                        .HasColumnName("lifecycle_status");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer")
                        .HasColumnName("track_number");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "LifecycleStatus");

                    b.HasIndex("ReleaseId", "TrackNumber")
                        .IsUnique();

                    b.ToTable("track", "catalog");
                });

            modelBuilder.Entity("Amuse.Modules.Catalog.Processing.AudioTranscodeJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MasterKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("master_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("stream_key");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("audio_transcode_job", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseCollaborator", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amuse.Domain.Catalog.Release", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Track", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Release", null)
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Release", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
