// <auto-generated />
using System;
using Amuse.Domain.Catalog;
using Amuse.Modules.Catalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amuse.Modules.Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260607042925_AddAudioIngestHardening")]
    partial class AddAudioIngestHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "artist_visibility_tier", new[] { "unverified", "platform_verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "audio_codec", new[] { "flac", "opus", "aac" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "audio_transcode_job_status", new[] { "queued", "processing", "succeeded", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "release_collaborator_role", new[] { "featured" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "release_lifecycle_status", new[] { "draft", "processing", "ready", "published", "hidden", "archived", "scheduled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "release_type", new[] { "single", "ep", "album", "compilation" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "catalog", "track_lifecycle_status", new[] { "draft", "processing", "ready", "published", "hidden" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amuse.Domain.Catalog.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("aliases");

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_key");

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("bio");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CoverKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cover_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ManagingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("managing_organization_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.Property<ArtistVisibilityTier>("VisibilityTier")
                        .HasColumnType("catalog.artist_visibility_tier")
                        .HasColumnName("visibility_tier");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("ManagingOrganizationId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("artist", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("CLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("c_line");

                    b.Property<string>("CoverArtKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cover_art_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("LabelName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label_name");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language_code");

                    b.Property<ReleaseLifecycleStatus>("LifecycleStatus")
                        .HasColumnType("catalog.release_lifecycle_status")
                        .HasColumnName("lifecycle_status");

                    b.Property<bool>("MetadataComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("metadata_complete");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("OriginalReleaseDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("original_release_date");

                    b.Property<string>("PLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("p_line");

                    b.Property<string>("PrimaryGenre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_genre");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("ReleaseDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("release_date");

                    b.Property<Guid?>("ReleaseGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_group_id");

                    b.Property<ReleaseType>("ReleaseType")
                        .HasColumnType("catalog.release_type")
                        .HasColumnName("release_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Upc")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("upc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("ReleaseGroupId");

                    b.HasIndex("Upc");

                    b.HasIndex("ArtistId", "Slug")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "LifecycleStatus", "ReleaseDate");

                    b.ToTable("release", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseCollaborator", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<ReleaseCollaboratorRole>("Role")
                        .HasColumnType("catalog.release_collaborator_role")
                        .HasColumnName("role");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.HasKey("ReleaseId", "ArtistId", "Role");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ReleaseId", "DisplayOrder");

                    b.ToTable("release_collaborator", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ArtistId", "Slug")
                        .IsUnique();

                    b.ToTable("release_group", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioMasterKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audio_master_key");

                    b.Property<string>("AudioStreamKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audio_stream_key");

                    b.Property<string>("ComposerCredits")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("composer_credits");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<bool>("ExplicitFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("explicit_flag");

                    b.Property<string>("Isrc")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("isrc");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language_code");

                    b.Property<TrackLifecycleStatus>("LifecycleStatus")
                        .HasColumnType("catalog.track_lifecycle_status")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Lyrics")
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)")
                        .HasColumnName("lyrics");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer")
                        .HasColumnName("track_number");

                    b.Property<string>("VersionTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("version_title");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "LifecycleStatus");

                    b.HasIndex("ReleaseId", "TrackNumber")
                        .IsUnique();

                    b.ToTable("track", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.TrackAudioRendition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdaptationSetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("adaptation_set_id");

                    b.Property<int>("Bandwidth")
                        .HasColumnType("integer")
                        .HasColumnName("bandwidth");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("integer")
                        .HasColumnName("bitrate_kbps");

                    b.Property<AudioCodec>("Codec")
                        .HasColumnType("catalog.audio_codec")
                        .HasColumnName("codec");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("manifest_id");

                    b.Property<string>("RepresentationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("representation_id");

                    b.Property<int>("SampleRateHz")
                        .HasColumnType("integer")
                        .HasColumnName("sample_rate_hz");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "Codec", "BitrateKbps")
                        .IsUnique();

                    b.ToTable("track_audio_rendition", "catalog");
                });

            modelBuilder.Entity("Amuse.Modules.Catalog.Messaging.CatalogOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", "catalog");
                });

            modelBuilder.Entity("Amuse.Modules.Catalog.Processing.AudioMasterUploadIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("TrackId", "ConsumedAt");

                    b.ToTable("audio_master_upload_intent", "catalog");
                });

            modelBuilder.Entity("Amuse.Modules.Catalog.Processing.AudioTranscodeJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MasterKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("master_key");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("stream_key");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("audio_transcode_job", "catalog");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Release", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.ReleaseGroup", null)
                        .WithMany()
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseCollaborator", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amuse.Domain.Catalog.Release", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseGroup", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Track", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Release", null)
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Amuse.Domain.Catalog.TrackLoudnessProfile", "LoudnessProfile", b1 =>
                        {
                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AnalyzedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("loudness_analyzed_at");

                            b1.Property<double>("IntegratedLufs")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_integrated_lufs");

                            b1.Property<double>("LinearGainLu")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_linear_gain_lu");

                            b1.Property<double>("LoudnessRangeLu")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_range_lu");

                            b1.Property<double>("TargetIntegratedLufs")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_target_integrated_lufs");

                            b1.Property<double>("TargetTruePeakDbtp")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_target_true_peak_dbtp");

                            b1.Property<double>("ThresholdLufs")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_threshold_lufs");

                            b1.Property<double>("TruePeakDbtp")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_true_peak_dbtp");

                            b1.HasKey("TrackId");

                            b1.ToTable("track", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("LoudnessProfile");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.TrackAudioRendition", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Release", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
