// <auto-generated />
using System;
using Amuse.Domain.Tenancy;
using Amuse.Modules.Tenancy.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amuse.Modules.Tenancy.Persistence.Migrations
{
    [DbContext(typeof(TenancyDbContext))]
    [Migration("20260530145956_AddOrganizationInvitesAndMigrateClaims")]
    partial class AddOrganizationInvitesAndMigrateClaims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenancy")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tenancy", "org_class", new[] { "indie_group", "backing_org" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tenancy", "organization_lifecycle_status", new[] { "draft", "active", "suspended", "closed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tenancy", "organization_onboarding_status", new[] { "not_required", "pending_review", "approved", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tenancy", "organization_trust_tier", new[] { "unverified", "identity_verified", "platform_verified" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amuse.Domain.Tenancy.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by_operator_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<OrganizationLifecycleStatus>("LifecycleStatus")
                        .HasColumnType("tenancy.organization_lifecycle_status")
                        .HasColumnName("lifecycle_status");

                    b.Property<OrganizationOnboardingStatus>("OnboardingStatus")
                        .HasColumnType("tenancy.organization_onboarding_status")
                        .HasColumnName("onboarding_status");

                    b.Property<OrganizationClass>("OrgClass")
                        .HasColumnType("tenancy.org_class")
                        .HasColumnName("org_class");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_reason");

                    b.Property<OrganizationTrustTier>("TrustTier")
                        .HasColumnType("tenancy.organization_trust_tier")
                        .HasColumnName("trust_tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingStatus");

                    b.HasIndex("OrgClass");

                    b.ToTable("organization", "tenancy");
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.OrganizationInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_account_id");

                    b.Property<string>("Claims")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("claims");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_account_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PresetRoleLabel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("preset_role_label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Email", "Status")
                        .IsUnique()
                        .HasFilter("status = 'Pending'");

                    b.ToTable("organization_invite", "tenancy");
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Claims")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("claims");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PresetRoleLabel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("preset_role_label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrganizationId", "AccountId")
                        .IsUnique();

                    b.ToTable("organization_member", "tenancy");
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.OrganizationInvite", b =>
                {
                    b.HasOne("Amuse.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.OrganizationMember", b =>
                {
                    b.HasOne("Amuse.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
