// <auto-generated />
using System;
using Amuse.Domain.Billing;
using Amuse.Modules.Billing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amuse.Modules.Billing.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260607194034_UpdatePurchaseEntitlementIndexes")]
    partial class UpdatePurchaseEntitlementIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "entitlement_status", new[] { "active", "revoked" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "entry_direction", new[] { "credit", "debit" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "fx_rate_source", new[] { "ecb_daily", "ops_manual", "stripe_quote" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "journal_type", new[] { "adjustment", "chargeback", "hold_release", "purchase", "refund", "stream_settlement", "withdrawal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "ledger_account_type", new[] { "platform_cash", "platform_revenue", "psp_fee_expense", "refund_liability", "seller_payable_available", "seller_payable_in_payout", "seller_payable_pending", "vat_payable" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "legal_entity_type", new[] { "company", "individual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "payment_status", new[] { "charged_back", "free", "paid", "partially_refunded", "pending", "refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "payout_rail", new[] { "manual_bank", "stripe_global" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "payout_verification_status", new[] { "not_started", "rejected", "submitted", "under_review", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "purchased_unit", new[] { "release", "track" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "reference_type", new[] { "adjustment", "chargeback", "purchase", "refund", "stream_settlement", "withdrawal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "refund_fee_bearer", new[] { "platform", "seller" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing", "withdrawal_status", new[] { "approved", "completed", "failed", "pending_approval", "processing", "requested" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amuse.Domain.Billing.BannedPaymentInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BannedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("banned_at");

                    b.Property<string>("PaymentMethodFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("payment_method_fingerprint");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodFingerprint")
                        .IsUnique();

                    b.ToTable("banned_payment_instrument", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("effective_at");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("imported_at");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("quote_currency");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("rate");

                    b.Property<FxRateSource>("Source")
                        .HasColumnType("billing.fx_rate_source")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency", "QuoteCurrency", "EffectiveAt");

                    b.ToTable("fx_rate", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<LedgerAccountType>("AccountType")
                        .HasColumnType("billing.ledger_account_type")
                        .HasColumnName("account_type");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<EntryDirection>("Direction")
                        .HasColumnType("billing.entry_direction")
                        .HasColumnName("direction");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.ToTable("ledger_entry", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.LedgerJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AvailableAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("available_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<JournalType>("JournalType")
                        .HasColumnType("billing.journal_type")
                        .HasColumnName("journal_type");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("posted_at");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<ReferenceType>("ReferenceType")
                        .HasColumnType("billing.reference_type")
                        .HasColumnName("reference_type");

                    b.HasKey("Id");

                    b.ToTable("ledger_journal", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long>("GrossMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_minor");

                    b.Property<string>("PaymentMethodFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("payment_method_fingerprint");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_reference");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<PaymentStatus>("Status")
                        .HasColumnType("billing.payment_status")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("payment_transaction", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.PayoutProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalRecipientId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_recipient_id");

                    b.Property<LegalEntityType>("LegalEntityType")
                        .HasColumnType("billing.legal_entity_type")
                        .HasColumnName("legal_entity_type");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("legal_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<PayoutRail>("PayoutRail")
                        .HasColumnType("billing.payout_rail")
                        .HasColumnName("payout_rail");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<PayoutVerificationStatus>("VerificationStatus")
                        .HasColumnType("billing.payout_verification_status")
                        .HasColumnName("verification_status");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("payout_profile", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<EntitlementStatus>("EntitlementStatus")
                        .HasColumnType("billing.entitlement_status")
                        .HasColumnName("entitlement_status");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("paid_at");

                    b.Property<PaymentStatus>("PaymentStatus")
                        .HasColumnType("billing.payment_status")
                        .HasColumnName("payment_status");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<long>("PriceSnapshotMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("price_snapshot_minor");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("purchased_at");

                    b.Property<PurchasedUnit>("PurchasedUnit")
                        .HasColumnType("billing.purchased_unit")
                        .HasColumnName("purchased_unit");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ReleaseId")
                        .IsUnique()
                        .HasFilter("release_id IS NOT NULL AND purchased_unit = 'release' AND entitlement_status = 'active'");

                    b.HasIndex("AccountId", "TrackId")
                        .IsUnique()
                        .HasFilter("track_id IS NOT NULL AND entitlement_status = 'active'");

                    b.ToTable("purchase", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.PurchaseAllocationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("PayeeOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_organization_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<int>("ShareBps")
                        .HasColumnType("integer")
                        .HasColumnName("share_bps");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.ToTable("purchase_allocation_snapshot", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.SellerReceivable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_settled");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("settled_at");

                    b.HasKey("Id");

                    b.ToTable("seller_receivable", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.TaxInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long>("GrossMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_minor");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<long>("NetExVatMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("net_ex_vat_minor");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<long>("VatMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_minor");

                    b.Property<int>("VatRateBps")
                        .HasColumnType("integer")
                        .HasColumnName("vat_rate_bps");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("tax_invoice", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("FxRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("fx_rate_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("requested_at");

                    b.Property<WithdrawalStatus>("Status")
                        .HasColumnType("billing.withdrawal_status")
                        .HasColumnName("status");

                    b.Property<string>("TransferReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("transfer_reference");

                    b.HasKey("Id");

                    b.ToTable("withdrawal_request", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("aliases");

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_key");

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("bio");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("CoverKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cover_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ManagingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("managing_organization_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.Property<int>("VisibilityTier")
                        .HasColumnType("catalog.artist_visibility_tier")
                        .HasColumnName("visibility_tier");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("ManagingOrganizationId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("artist", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("CLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("c_line");

                    b.Property<string>("CoverArtKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cover_art_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_sale");

                    b.Property<string>("LabelName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label_name");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language_code");

                    b.Property<int>("LifecycleStatus")
                        .HasColumnType("catalog.release_lifecycle_status")
                        .HasColumnName("lifecycle_status");

                    b.Property<bool>("MetadataComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("metadata_complete");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("OriginalReleaseDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("original_release_date");

                    b.Property<string>("PLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("p_line");

                    b.Property<long?>("PriceCeilingMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("price_ceiling_minor");

                    b.Property<string>("PriceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("price_currency");

                    b.Property<long>("PriceFloorMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("price_floor_minor");

                    b.Property<string>("PrimaryGenre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_genre");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("ReleaseDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("release_date");

                    b.Property<Guid?>("ReleaseGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_group_id");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("catalog.release_type")
                        .HasColumnName("release_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Upc")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("upc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("ReleaseGroupId");

                    b.HasIndex("Upc");

                    b.HasIndex("ArtistId", "Slug")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "LifecycleStatus", "ReleaseDate");

                    b.ToTable("release", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseCollaborator", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<int>("Role")
                        .HasColumnType("catalog.release_collaborator_role")
                        .HasColumnName("role");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.HasKey("ReleaseId", "ArtistId", "Role");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ReleaseId", "DisplayOrder");

                    b.ToTable("release_collaborator", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ArtistId", "Slug")
                        .IsUnique();

                    b.ToTable("release_group", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.RoyaltySplit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("effective_from");

                    b.Property<Guid>("ListingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_organization_id");

                    b.Property<Guid>("PayeeOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_organization_id");

                    b.Property<int>("ShareBps")
                        .HasColumnType("integer")
                        .HasColumnName("share_bps");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.HasIndex("ListingOrganizationId");

                    b.HasIndex("TrackId", "PayeeOrganizationId")
                        .IsUnique();

                    b.ToTable("royalty_split", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioMasterKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audio_master_key");

                    b.Property<string>("AudioStreamKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audio_stream_key");

                    b.Property<string>("ComposerCredits")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("composer_credits");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<bool>("ExplicitFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("explicit_flag");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_sale");

                    b.Property<string>("Isrc")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("isrc");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language_code");

                    b.Property<int>("LifecycleStatus")
                        .HasColumnType("catalog.track_lifecycle_status")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Lyrics")
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)")
                        .HasColumnName("lyrics");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long?>("PriceCeilingMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("price_ceiling_minor");

                    b.Property<string>("PriceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("price_currency");

                    b.Property<long>("PriceFloorMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("price_floor_minor");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer")
                        .HasColumnName("track_number");

                    b.Property<string>("VersionTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("version_title");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "LifecycleStatus");

                    b.HasIndex("ReleaseId", "TrackNumber")
                        .IsUnique();

                    b.ToTable("track", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.TrackAudioRendition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdaptationSetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("adaptation_set_id");

                    b.Property<int>("Bandwidth")
                        .HasColumnType("integer")
                        .HasColumnName("bandwidth");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("integer")
                        .HasColumnName("bitrate_kbps");

                    b.Property<int>("Codec")
                        .HasColumnType("catalog.audio_codec")
                        .HasColumnName("codec");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uuid")
                        .HasColumnName("manifest_id");

                    b.Property<string>("RepresentationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("representation_id");

                    b.Property<int>("SampleRateHz")
                        .HasColumnType("integer")
                        .HasColumnName("sample_rate_hz");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "Codec", "BitrateKbps")
                        .IsUnique();

                    b.ToTable("track_audio_rendition", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.LibraryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Kind")
                        .HasColumnType("discovery.library_entry_kind")
                        .HasColumnName("kind");

                    b.Property<Guid>("ListenerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("listener_profile_id");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("saved_at");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("ListenerProfileId", "Kind");

                    b.HasIndex("ListenerProfileId", "Kind", "TargetId")
                        .IsUnique();

                    b.ToTable("library_entry", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ForkedFromPlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("forked_from_playlist_id");

                    b.Property<int>("Kind")
                        .HasColumnType("discovery.playlist_kind")
                        .HasColumnName("kind");

                    b.Property<Guid>("OwnerListenerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_listener_profile_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("discovery.playlist_visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("OwnerListenerProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_playlist_owner_liked_unique")
                        .HasFilter("kind = 'liked'::discovery.playlist_kind");

                    b.HasIndex("Visibility", "Title");

                    b.ToTable("playlist", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistFollow", b =>
                {
                    b.Property<Guid>("ListenerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("listener_profile_id");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<DateTimeOffset>("FollowedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("followed_at");

                    b.HasKey("ListenerProfileId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("playlist_follow", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("playlist_id")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.HasKey("Id");

                    b.HasIndex("playlist_id", "Position")
                        .IsUnique();

                    b.HasIndex("playlist_id", "TrackId")
                        .IsUnique();

                    b.ToTable("playlist_item", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistShareGrant", b =>
                {
                    b.Property<Guid>("playlist_id")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("granted_at");

                    b.HasKey("playlist_id", "Email");

                    b.ToTable("playlist_share_grant", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("banned_at");

                    b.Property<string>("IdpIssuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idp_issuer");

                    b.Property<string>("IdpSubject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("idp_subject");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdpIssuer", "IdpSubject")
                        .IsUnique();

                    b.ToTable("account", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_session", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Listener.ListenerPreference", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool?>("AllowUnverifiedArtists")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_unverified_artists");

                    b.Property<bool>("SetDuringOnboarding")
                        .HasColumnType("boolean")
                        .HasColumnName("set_during_onboarding");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId");

                    b.ToTable("listener_preference", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Listener.ListenerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int?>("AvatarAccentSeed")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_accent_seed");

                    b.Property<string>("AvatarObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_object_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("listener_profile", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Platform.PlatformOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Claims")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("claims");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("platform_operator", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.BusinessPortalProfile", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int?>("AvatarAccentSeed")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_accent_seed");

                    b.Property<string>("AvatarObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_object_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId");

                    b.ToTable("business_portal_profile", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedByOperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by_operator_id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("ImprintName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("imprint_name");

                    b.Property<int>("LifecycleStatus")
                        .HasColumnType("tenancy.organization_lifecycle_status")
                        .HasColumnName("lifecycle_status");

                    b.Property<int>("OnboardingStatus")
                        .HasColumnType("tenancy.organization_onboarding_status")
                        .HasColumnName("onboarding_status");

                    b.Property<int>("OrgClass")
                        .HasColumnType("tenancy.org_class")
                        .HasColumnName("org_class");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("TrustTier")
                        .HasColumnType("tenancy.organization_trust_tier")
                        .HasColumnName("trust_tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingStatus");

                    b.HasIndex("OrgClass");

                    b.ToTable("organization", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.OrganizationInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_account_id");

                    b.Property<string>("Claims")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("claims");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_account_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PresetRoleLabel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("preset_role_label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Email", "Status")
                        .IsUnique()
                        .HasFilter("status = 'Pending'");

                    b.ToTable("organization_invite", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Claims")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("claims");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PresetRoleLabel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("preset_role_label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrganizationId", "AccountId")
                        .IsUnique();

                    b.ToTable("organization_member", "billing");
                });

            modelBuilder.Entity("Amuse.Modules.Audit.Persistence.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("table_name");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.ToTable("audit_log", "billing");
                });

            modelBuilder.Entity("Amuse.Modules.Catalog.Messaging.CatalogOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_message", "billing");
                });

            modelBuilder.Entity("Amuse.Modules.Catalog.Processing.AudioMasterUploadIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("TrackId", "ConsumedAt");

                    b.ToTable("audio_master_upload_intent", "billing");
                });

            modelBuilder.Entity("Amuse.Modules.Catalog.Processing.AudioTranscodeJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MasterKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("master_key");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("stream_key");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("audio_transcode_job", "billing");
                });

            modelBuilder.Entity("Amuse.Domain.Billing.LedgerEntry", b =>
                {
                    b.HasOne("Amuse.Domain.Billing.LedgerJournal", null)
                        .WithMany("Entries")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Release", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.ReleaseGroup", null)
                        .WithMany()
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseCollaborator", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amuse.Domain.Catalog.Release", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.ReleaseGroup", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Track", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Release", null)
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Amuse.Domain.Catalog.TrackLoudnessProfile", "LoudnessProfile", b1 =>
                        {
                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AnalyzedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("loudness_analyzed_at");

                            b1.Property<double>("IntegratedLufs")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_integrated_lufs");

                            b1.Property<double>("LinearGainLu")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_linear_gain_lu");

                            b1.Property<double>("LoudnessRangeLu")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_range_lu");

                            b1.Property<double>("TargetIntegratedLufs")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_target_integrated_lufs");

                            b1.Property<double>("TargetTruePeakDbtp")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_target_true_peak_dbtp");

                            b1.Property<double>("ThresholdLufs")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_threshold_lufs");

                            b1.Property<double>("TruePeakDbtp")
                                .HasColumnType("double precision")
                                .HasColumnName("loudness_true_peak_dbtp");

                            b1.HasKey("TrackId");

                            b1.ToTable("track", "billing");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("LoudnessProfile");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.TrackAudioRendition", b =>
                {
                    b.HasOne("Amuse.Domain.Catalog.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistItem", b =>
                {
                    b.HasOne("Amuse.Domain.Discovery.Playlist", null)
                        .WithMany("Items")
                        .HasForeignKey("playlist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.PlaylistShareGrant", b =>
                {
                    b.HasOne("Amuse.Domain.Discovery.Playlist", null)
                        .WithMany("ShareGrants")
                        .HasForeignKey("playlist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.OrganizationInvite", b =>
                {
                    b.HasOne("Amuse.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Tenancy.OrganizationMember", b =>
                {
                    b.HasOne("Amuse.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Amuse.Domain.Billing.LedgerJournal", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Amuse.Domain.Catalog.Release", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Amuse.Domain.Discovery.Playlist", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ShareGrants");
                });
#pragma warning restore 612, 618
        }
    }
}
